### ISSUE TITLE
Label for Rights Statement needs clean-up

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/hydrox#106]
When a work's metadata is displayed, the "Rights Statement" label has a straggling unnecessary word, "Tesim". That should go away. See screenshot

![screenshot 2018-01-16 15 20 02](https://user-images.githubusercontent.com/1801076/35017276-0018c170-fad1-11e7-82a6-1daf0daacfbb.png)

**Comment by aaron-collier** [comment]
Odd. I'll take a look, should be an easy fix.

**Comment by aaron-collier** [comment]
@hannahfrost I believe this can be closed as well. Can you verify?

**Comment by hannahfrost** [comment]
verified and closing!
