### ISSUE TITLE
Revise work show page

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/hydrox#13]
Re: https://github.com/samvera-labs/hyku/issues/1215

**Comment by hannahfrost** [comment]
And I just elaborated on the work in https://github.com/samvera/hyrax/issues/2050

**Comment by hannahfrost** [comment]
Does this ticket duplication #32 ?

**Comment by aaron-collier** [comment]
@hannahfrost - yeah I think so. I was breaking some of these down, and missed closing this one. Good catch :-)
