### ISSUE TITLE
Improve user experience for editing works

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/hydrox#15]
Re: https://github.com/samvera/hyrax/issues/1218

**Comment by hannahfrost** [comment]
Decomposed samvera/hyrax#1218 into the following tickets:

- [x] https://github.com/samvera/hyrax/issues/2025
- [x] https://github.com/samvera/hyrax/issues/2026
- [x] https://github.com/samvera/hyrax/issues/2028
- [x] https://github.com/samvera/hyrax/issues/2030
- [x] ~~https://github.com/samvera/hyrax/issues/2034~~
- [x] https://github.com/samvera/hyrax/issues/2242
- [x] https://github.com/samvera/hyrax/issues/2243
- [x] https://github.com/samvera/hyrax/issues/2245
- [x] https://github.com/samvera/hyrax/issues/2247
- [x] https://github.com/samvera/hyrax/issues/2248
- [x] https://github.com/samvera/hyrax/issues/2249
