### ISSUE TITLE
Revise homepage design

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/hydrox#16]
Re: https://github.com/samvera-labs/hyku/issues/457

**Comment by hannahfrost** [comment]
Let's implement this layout from Gary's design options (Example 1 from Hyku#457)
![example1](https://user-images.githubusercontent.com/1801076/33780482-ca254fdc-dc05-11e7-8569-cc36c042905a.png)

This calls for a "featured work" area. Can we add the ability to configure this work on the Admin Dashboard? I'll ticket that separately.

**Comment by mjgiarlo** [comment]
> This calls for a "featured work" area. Can we add the ability to configure this work on the Admin Dashboard? I'll ticket that separately.

:+1:, and I wonder too if we can expand Hyrax's "featured researcher" content block to be more configurable rather than adding a new block.

**Comment by hannahfrost** [comment]
@mjgiarlo Are you envisioning a single "featured" block that can be configured to be one of multiple options (researcher / work / collection)? That certainly would be elegant, but I wonder if we will eventually find a Hyrax implementor that wants to feature more than one things on the home page. Could one "block" on the dashboard page support multiple features, each of which could be displayed separately on the home page?

**Comment by hannahfrost** [comment]
The ticket for a basic configuration starting point is #85

**Comment by mjgiarlo** [comment]
@hannahfrost :speech_balloon: 
> Could one "block" on the dashboard page support multiple features, each of which could be displayed separately on the home page?

They'd be separate "content blocks" (using the verbiage built into Hyrax), but could display in a single UI block, I imagine.

**Comment by hannahfrost** [comment]
🆗
