### ISSUE TITLE
Insure proper treeification of DRUIDs

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/hydrox#19]
Our format of aannnaannnn differs from the default NOID format expected in ActiveFedora which results in misaligned treeification.

<img width="525" alt="screen shot 2017-10-19 at 3 38 43 pm" src="https://user-images.githubusercontent.com/2294288/31797591-e2b4062c-b4e3-11e7-9277-e2e0d199e218.png">

**Comment by aaron-collier** [comment]
This will most likely require #25

**Comment by mjgiarlo** [comment]
Do we consider this blocked or more of a `wontfix` (preferring instead to document this decision)?
