### ISSUE TITLE
QA the work workflow UI

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/hydrox#33]
https://github.com/samvera-labs/hyku/issues/1033

**Comment by mjgiarlo** [comment]
@aaron-collier Should this be assigned to you? Or is this not in progress?

**Comment by mjgiarlo** [comment]
@aaron-collier will pick this up after #3.

**Comment by aaron-collier** [comment]
I'm pretty sure this can be closed now, but will defer to @hannahfrost to verify. I'm seeing the changes in the latest pull from hyrax/master
