### ISSUE TITLE
QA the revised Add Work page

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/hydrox#34]
https://github.com/samvera/hyrax/issues/1218

## Parts:
 
- [x] https://github.com/samvera/hyrax/issues/2026
- [x] https://github.com/samvera/hyrax/issues/2025
- [x] https://github.com/samvera/hyrax/issues/2028
- [x] https://github.com/samvera/hyrax/issues/2030
- [x] ~~https://github.com/samvera/hyrax/issues/2034~~
- [x] https://github.com/samvera/hyrax/issues/2242
- [x] https://github.com/samvera/hyrax/issues/2243
- [x] https://github.com/samvera/hyrax/issues/2245
- [x] https://github.com/samvera/hyrax/issues/2247
- [x] https://github.com/samvera/hyrax/issues/2248
- [x] https://github.com/samvera/hyrax/issues/2249

**Comment by mjgiarlo** [comment]
All of these tickets are now done.

**Comment by mjgiarlo** [comment]
@hannahfrost will QA this functionality to ensure changes to Hyrax are now reflected in Hydrox.

**Comment by mjgiarlo** [comment]
@hannahfrost this is now ready to QA.

**Comment by aaron-collier** [comment]
I'm pretty sure we can close this now as the changes show up in the latest pull. But will defer to @hannahfrost verifying that.
