### ISSUE TITLE
Extract IIIF Presentation API implementation from Hyku into Hyrax

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/hydrox#77]

**Comment by mjgiarlo** [comment]
Hyku implementation, at a high level:

- [x] Depends on `iiif_manifest` gem
- [x] [A controller mixin that provides a manifest action, which returns a IIIF manifest for the presentation API](https://github.com/samvera-labs/hyku/pull/523) -- this is included in generated work type controllers
- [x] [Add member route to CC basic routes](https://github.com/samvera-labs/hyku/blob/5c7929309cdcc05ac95af04787abb3e3580417cf/config/routes.rb#L38-L40)
- [x] [A manifest-enabled work show presenter](https://github.com/samvera-labs/hyku/blob/d3131425a39c06848c9dac770c53ff0191110438/app/presenters/hyku/manifest_enabled_work_show_presenter.rb) -- consider doing this work in Hyrax's existing work show presenter
- [x] [A manifest helper builder](https://github.com/samvera-labs/hyku/pull/118) (used only in work show presenter)
- [x] [`DisplaysImage` mixin for FileSetPresenter](https://github.com/samvera-labs/hyku/blob/ba46d2fc17d74c59e5da274d7b6414254408558b/app/presenters/concerns/displays_image.rb)
- [x] Update Hydrox to use latest Hyrax and run riiif generator

**Comment by mjgiarlo** [comment]
@hannahfrost @aaron-collier What does done look like for this work? When IIIF image & presentation support land in Hydrox, or when the UV show page lands in Hydrox?

**Comment by hannahfrost** [comment]
@mjgiarlo I think it is done when the UV show page lands in Hydrox. Might be helpful to explicitly make that a second phase of work (and a separate ticket), since it involves third-party work (Julie).

**Comment by mjgiarlo** [comment]
OK. Will ticket that separately. Thanks, @hannahfrost!
