### ISSUE TITLE
Use UniversalViewer on the work show page

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/hydrox#88]
This work will be done in Hyrax, and will be taken on by Julie Allinson. The purpose of this ticket is to track that work, and make sure Hydrox is updated to use the latest commit of Hyrax once that work lands in Hyrax.

  - [ ] Pull in UniversalViewer and use when `Hyrax.config.iiif_image_server?` is `true`
  - [ ] Layer in the [`rendering_ids` change](https://github.com/samvera-labs/hyku/pull/1376)
  - [ ] Layer in [adding metadata to the manifest](https://github.com/samvera-labs/hyku/pull/1436)
  - [ ] Additional Javascript changes (mentioned by @geekscruff)

Tracking https://github.com/samvera/hyrax/issues/2345

**Comment by ghost** [comment]
@mjgiarlo I'm happy to do 2-4, but less sure about what 1 entails

**Comment by mjgiarlo** [comment]
@geekscruff Ah, OK! Let's start with 2-4, and I'll start looking into 1.

**Comment by ghost** [comment]
@mjgiarlo I'll try and get PRs for 2 and 3 in tomorrow, 4 is an improvement so could wait if I don't get enough time

**Comment by mjgiarlo** [comment]
@geekscruff :clap:
