### ISSUE TITLE
Thumbnails currently broken

### ISSUE THREAD

**Issue by eefahy** [sul-dlss/hydrox#90]
After uploading a PDF, all pages that try to display a thumbnail throw: https://app.honeybadger.io/projects/54378/faults/35855355

**Comment by aaron-collier** [comment]
Confirmed broken for images as well.

**Comment by aaron-collier** [comment]
May be related ~/ solved~ along with #61

**Comment by mjgiarlo** [comment]
Probably not solved, alas. It's a workaround for image-like files at best. :frowning_face:

**Comment by hannahfrost** [comment]
Path forward for now: set up a local mount for files.
